# Generated by Django 5.1.6 on 2025-03-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/profile_pics/default.jpg', null=True, upload_to='static/profile_pics/'),
        ),
    ]
